// DHT11 - Version: Latest

/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/ca98a328-babd-4620-85b1-b5708f1e14fe

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humi;
  float temp;
  bool ledstatus;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>

int led = D1;
DHT dht(D2, DHT11);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(led, OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  dht.begin();
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  temp = dht.readTemperature();
  humi = dht.readHumidity();
  if(ledstatus) {
    digitalWrite(led, HIGH);
  }
  else {
    digitalWrite(led, LOW);
  }
}






/*
  Since Ledstatus is READ_WRITE variable, onLedstatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedstatusChange()  {
  // Add your code here to act upon Ledstatus change
}
